/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocialIndexRouteImport } from './routes/social.index'
import { Route as SocialDescubrirRouteImport } from './routes/social.descubrir'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialIndexRoute = SocialIndexRouteImport.update({
  id: '/social/',
  path: '/social/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialDescubrirRoute = SocialDescubrirRouteImport.update({
  id: '/social/descubrir',
  path: '/social/descubrir',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/social/descubrir': typeof SocialDescubrirRoute
  '/social/': typeof SocialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/social/descubrir': typeof SocialDescubrirRoute
  '/social': typeof SocialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/social/descubrir': typeof SocialDescubrirRoute
  '/social/': typeof SocialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/social/descubrir' | '/social/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/social/descubrir' | '/social'
  id: '__root__' | '/' | '/social/descubrir' | '/social/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SocialDescubrirRoute: typeof SocialDescubrirRoute
  SocialIndexRoute: typeof SocialIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/': {
      id: '/social/'
      path: '/social'
      fullPath: '/social/'
      preLoaderRoute: typeof SocialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/descubrir': {
      id: '/social/descubrir'
      path: '/social/descubrir'
      fullPath: '/social/descubrir'
      preLoaderRoute: typeof SocialDescubrirRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SocialDescubrirRoute: SocialDescubrirRoute,
  SocialIndexRoute: SocialIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
